### ISSUE TITLE
nil pointer panic only when debugging

### ISSUE THREAD

**Issue by liuq19** [bytedance/sonic#126]
code:
```
package main_test

import (
        "runtime/debug"
	"testing"

	"github.com/bytedance/sonic"
)

func TestBuild(t *testing.T) {
         debug.SetGCPercent(-1)
	data := &Data{
		Details: []*Detail{
			{
				Info: Info{},
			},
		},
	}

	body, err := sonic.Marshal(data) // PANIC position only when DEBUG
	if err != nil {
		t.Error(err)
		return
	}
	t.Log(string(body))
}

type Detail struct {
	Info Info
}

type Info struct {
	A int  // COMMENT this may not panic
}

type Data struct {
	Details []*Detail
}
```

**Comment by liuq19** [comment]
panic log:
```
Starting: /Users/bytedance/go1.16/bin/dlv-dap dap --listen=127.0.0.1:50800 --log-dest=3 from /Users/bytedance/sonic-problem/panic1105
DAP server listening at: 127.0.0.1:50800
--- FAIL: TestBuild (4.15s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16fb106]

goroutine 34 [running]:
testing.tRunner.func1.2(0x1396bc0, 0x1529ed0)
	/usr/local/opt/go1.16/libexec/src/testing/testing.go:1143 +0x585
testing.tRunner.func1(0xc000118480)
	/usr/local/opt/go1.16/libexec/src/testing/testing.go:1146 +0x3c8
panic(0x1396bc0, 0x1529ed0)
	/usr/local/opt/go1.16/libexec/src/runtime/panic.go:971 +0x4c7
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc00010e3a8, 0x139bd20, 0xc0005b9a60, 0xc000380000, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.16/pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.1/encoder/primitives.go:74 +0x122
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc00010e3a8, 0x1388140, 0xc00009e1b8, 0xc000380000, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.16/pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.1/encoder/primitives.go:76 +0x18a
github.com/bytedance/sonic/encoder.EncodeInto(0xc00010e3a8, 0x1388140, 0xc00010e390, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.16/pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.1/encoder/encoder.go:102 +0x105
github.com/bytedance/sonic/encoder.Encode(0x1388140, 0xc00010e390, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.16/pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.1/encoder/encoder.go:80 +0xdc
github.com/bytedance/sonic.Marshal(0x1388140, 0xc00010e390, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bytedance/go1.16/pkg/mod/github.com/bytedance/sonic@v1.0.0-rc.1/sonic.go:35 +0x91
sonicpro/panic1105_test.TestBuild(0xc000118480)
	/Users/bytedance/sonic-problem/panic1105/main_test.go:18 +0x14d
testing.tRunner(0xc000118480, 0x13e2650)
	/usr/local/opt/go1.16/libexec/src/testing/testing.go:1193 +0x1a3
created by testing.(*T).Run
	/usr/local/opt/go1.16/libexec/src/testing/testing.go:1238 +0x63c
Process 18804 has exited with status 2
Detaching
dlv dap (18773) exited with code: 0
```
