### ISSUE TITLE
nil pointer panic when referencing return error in encodeTypedPointer()

### ISSUE THREAD

**Issue by liuq19** [bytedance/sonic#128]
```
package main_test

import (
        "runtime/debug"
	"testing"

	"github.com/bytedance/sonic"
)

func TestBuild(t *testing.T) {
         debug.SetGCPercent(-1)
	data := &Data{
		Details: []*Detail{
			{
				Info: Info{},
			},
		},
	}

	body, err := sonic.Marshal(data)
	if err != nil {
		t.Error(err)
		return
	}
	t.Log(string(body))
}

type Detail struct {
	Info Info
}

type Info struct {
	A int 
}

type Data struct {
	Details []*Detail
}

```

**Comment by liuq19** [comment]
This will cause panic when when reference return error in encodeTypedPointer() 

```
func encodeTypedPointer(buf *[]byte, vt *rt.GoType, vp *unsafe.Pointer, sb *_Stack, fv uint64) (ret error) {
    println("vp is ",  vp, " , *vp is ", *vp)
    println("ret address ", &ret) // 引用 ret 就报错
    if vt == nil {
        return encodeNil(buf)
    } else if fn, err := findOrCompile(vt); err != nil {
        return err
    } else if (vt.KindFlags & rt.F_direct) == 0 {
        return fn(buf, *vp, sb, fv)
    } else {
        return fn(buf, unsafe.Pointer(vp), sb, fv)
    }
}
```

**Comment by liuq19** [comment]
panic log:
```
➜  issue_test git:(feat/fake_loader) ✗ go test -v -run TestIssueDebug
=== RUN   TestIssueDebug
vp is  0xc000099458  , *vp is  0xc0000b2ba0
ret address  0xc00005ce48
vp is  0xc0000d7d58  , *vp is  0x0
ret address  0xc0000d7d50
--- FAIL: TestIssueDebug (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d710df]

goroutine 19 [running]:
testing.tRunner.func1.1(0x13c6ea0, 0x166ad40)
        /usr/local/opt/go1.15/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000082a80)
        /usr/local/opt/go1.15/libexec/src/testing/testing.go:1075 +0x41a
panic(0x13c6ea0, 0x166ad40)
        /usr/local/opt/go1.15/libexec/src/runtime/panic.go:969 +0x1b9
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc0000b2bc0, 0x13ce440, 0xc0000d7d58, 0xc000300000, 0x0, 0x0, 0x0)
        /Users/bytedance/sonic-master/encoder/primitives.go:76 +0x1da
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc0000b2bc0, 0x13a96a0, 0xc000099458, 0xc000300000, 0x0, 0x0, 0x0)
        /Users/bytedance/sonic-master/encoder/primitives.go:78 +0x22a
github.com/bytedance/sonic/encoder.EncodeInto(0xc0000b2bc0, 0x13a96a0, 0xc0000b2ba0, 0x0, 0xc00004a708, 0xc00004a700)
        /Users/bytedance/sonic-master/encoder/encoder.go:102 +0xe5
github.com/bytedance/sonic/encoder.Encode(0x13a96a0, 0xc0000b2ba0, 0x0, 0x42adc54138b1, 0x19fb5248, 0x19fb52480000000f, 0x6188eb70, 0xc00004a770)
        /Users/bytedance/sonic-master/encoder/encoder.go:80 +0xbd
github.com/bytedance/sonic.Marshal(...)
        /Users/bytedance/sonic-master/sonic.go:35
github.com/bytedance/sonic/issue_test_test.TestIssueDebug(0xc000082a80)
        /Users/bytedance/sonic-master/issue_test/issuexxxxdebug_test.go:30 +0xd2
testing.tRunner(0xc000082a80, 0x1439878)
        /usr/local/opt/go1.15/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/local/opt/go1.15/libexec/src/testing/testing.go:1168 +0x2b3
exit status 2
FAIL    github.com/bytedance/sonic/issue_test   1.250s
````

**Comment by liuq19** [comment]
in debug mode， the error arg in encodeTypedPointer will be initialized as nil. 
so the stored _VAR_vp (in the position of the err arg) will become nil.
