### ISSUE TITLE
go test would fail when GO111MODULE=off

### ISSUE THREAD

**Issue by ericuni** [bytedance/sonic#176]
prepare env
```bash
export GO111MODULE="on"
git clone https://github.com/bytedance/sonic.git
cd sonic

go mod vendor
```

run go test with GOPATH mode
```bash
GO111MODULE=off go test -v
```
would fail with the following error
```plain
Begin GC looping...
=== RUN   TestDecodeFloat
--- PASS: TestDecodeFloat (0.01s)
=== RUN   TestMarshal
--- FAIL: TestMarshal (0.06s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 9 [running]:
testing.tRunner.func1.2({0x6a9ae0, 0x8cf6d0})
	/home/liuqi.victor/opt/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/liuqi.victor/opt/go/src/testing/testing.go:1212 +0x218
panic({0x6a9ae0, 0x8cf6d0})
	/home/liuqi.victor/opt/go/src/runtime/panic.go:1038 +0x215
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc0002a6060, 0x6d7d00, 0xc00029e068, 0x7f551ed74528, 0x0)
	/home/liuqi.victor/go/src/github.com/bytedance/sonic/encoder/primitives.go:75 +0x10d
github.com/bytedance/sonic/encoder.EncodeInto(0xc0002a6060, {0x6d7d00, 0xc000258d80}, 0x0)
	/home/liuqi.victor/go/src/github.com/bytedance/sonic/encoder/encoder.go:125 +0xf1
github.com/bytedance/sonic/encoder.Encode({0x6d7d00, 0xc000258d80}, 0x0)
	/home/liuqi.victor/go/src/github.com/bytedance/sonic/encoder/encoder.go:99 +0xc5
github.com/bytedance/sonic.Marshal(...)
	/home/liuqi.victor/go/src/github.com/bytedance/sonic/sonic.go:36
github.com/bytedance/sonic.TestMarshal(0xc0000ba4e0)
	/home/liuqi.victor/go/src/github.com/bytedance/sonic/decode_test.go:1023 +0x3a
testing.tRunner(0xc0000ba4e0, 0x6f8688)
	/home/liuqi.victor/opt/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/home/liuqi.victor/opt/go/src/testing/testing.go:1306 +0x35a
exit status 2
FAIL	github.com/bytedance/sonic	0.083s
```

part go env
```plain
GO111MODULE="on"
GOARCH="amd64"
GOVERSION="go1.17.5"
```

**Comment by AsterDY** [comment]
Why need `GO111MODULE=off`? It may impact go `linkname` which is used for sonic

**Comment by ericuni** [comment]
I'm working on a repo in my company, this repo depends on another repo which has no go.mod.
And I want to debug this dependency, as `go mod replace` does not support thouse repos without go.mod, so I tried to use `go mod vendor` to make everything local, then I encountered this porblem with another dependency sonic.

**Comment by AsterDY** [comment]
I used `go mod vendor` to test but did not find any problems. Could you give some reproducible codes?

**Comment by ericuni** [comment]
Did you run with go mod off `GO111MODULE=off go test -v`, I just tried the main branch, it's still the same error.

**Comment by chenzhuoyu** [comment]
Closed due to lack of activity.

@ericuni Also, `go vendor` was deprecated a long time ago and pretty much like a relic, a better solution is probably to upgrade those legacy dependencies.
