### ISSUE TITLE
Pass `[]byte(string)` to `Unmarshal()` or pass `string([]byte)` to `UnmarshalString()` may cause GC problem

### ISSUE THREAD

**Issue by AsterDY** [bytedance/sonic#186]
When using sonic's API abnormally and inefficiently copy origin JSON like below: 
```
type GlobalConfig []Conf

type Conf struct {
    A  string             `json:"A"`
    B  SubConf            `json:"B"`
    C []string            `json:"C"`
}

type SubConf struct {
    Slice        []int64 `json:"Slice"`
    Map          map[int64]bool `json:"-"`
}

func Reload(rawData string) {
    var tmp GlobalConfig
    err := sonic.Unmarshal([]byte(rawData), &tmp) // better use sonic.UnmarshalString()!
    if err != nil {
        t.Fatalf("failed to unmarshal json, raw data: %v, err: %v", rawData, err)
    }
}
```
In extremely heavy load (ex: 10000+goroutines * 100+times), may produce GC problems like:
```
runtime: marked free object in span 0x29a93db0, elemsize=320 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc09fcfe000 free  unmarked
0xc09fcfe140 alloc marked
0xc09fcfe280 free  unmarked
0xc09fcfe3c0 alloc marked
0xc09fcfe500 free  unmarked
0xc09fcfe640 alloc marked
0xc09fcfe780 free  unmarked
0xc09fcfe8c0 alloc marked
0xc09fcfea00 alloc unmarked
0xc09fcfeb40 alloc unmarked
0xc09fcfec80 alloc unmarked
0xc09fcfedc0 alloc unmarked
0xc09fcfef00 alloc unmarked
0xc09fcff040 alloc unmarked
0xc09fcff180 free  unmarked
0xc09fcff2c0 alloc marked
0xc09fcff400 free  unmarked
0xc09fcff540 free  marked   zombie
0x000000c09fcff540:  0x6966657270227b5b  0x656d6167223a2278
0x000000c09fcff550:  0x7276635f7961705f  0x65746c6966222c22
0x000000c09fcff560:  0x746972227b3a2272  0x36313033325b3a22
0x000000c09fcff570:  0x7265747865222c5d  0x697463615f6c616e
0x000000c09fcff580:  0x5d34315b3a226e6f  0x5f7473726966222c
0x000000c09fcff590:  0x7972747375646e69  0x39315b3a2264695f
0x000000c09fcff5a0:  0x227b2c7d7d5d3331  0x3a22786966657270
0x000000c09fcff5b0:  0x76635f646c6f6722  0x746c6966222c2272
0x000000c09fcff5c0:  0x6972227b3a227265  0x313030325b3a2274
0x000000c09fcff5d0:  0x675f7369222c5d36  0x726575715f646c6f
0x000000c09fcff5e0:  0x67222c7d313a2279  0x2279625f70756f72
0x000000c09fcff5f0:  0x7265747865225b3a  0x697463615f6c616e
0x000000c09fcff600:  0x227b2c7d5d226e6f  0x3a22786966657270
0x000000c09fcff610:  0x3364616576696c22  0x6c6966222c223430
0x000000c09fcff620:  0x72227b3a22726574  0x3030345b3a227469
0x000000c09fcff630:  0x6f7267222c5d3631  0x22657079745f7075
0x000000c09fcff640:  0x222c5d3430335b3a  0x6e676961706d6163
0x000000c09fcff650:  0x5b3a22657079745f  0x6f7267222c7d5d32
0x000000c09fcff660:  0x5b3a2279625f7075  0x616e726574786522
0x000000c09fcff670:  0x6e6f697463615f6c  0x000000005d7d5d22
0xc09fcff680 alloc marked
0xc09fcff7c0 alloc marked
0xc09fcff900 free  unmarked
0xc09fcffa40 alloc marked
0xc09fcffb80 free  unmarked
0xc09fcffcc0 alloc marked
0xc09fcffe00 free  unmarked
fatal error: found pointer to free object

goroutine 765 [running]:
runtime.throw({0x1357340, 0xc09fcff680})
	/usr/local/go1.17/src/runtime/panic.go:1198 +0x71 fp=0xc066de5b68 sp=0xc066de5b38 pc=0x1036311
runtime.(*mspan).reportZombies(0x29a93db0)
	/usr/local/go1.17/src/runtime/mgcsweep.go:691 +0x2e5 fp=0xc066de5be8 sp=0xc066de5b68 pc=0x1024cc5
runtime.(*sweepLocked).sweep(0x15f6580, 0x0)
	/usr/local/go1.17/src/runtime/mgcsweep.go:524 +0x8c5 fp=0xc066de5cc0 sp=0xc066de5be8 pc=0x10246c5
runtime.sweepone()
	/usr/local/go1.17/src/runtime/mgcsweep.go:290 +0x109 fp=0xc066de5d30 sp=0xc066de5cc0 pc=0x1023829
runtime.gcStart({0xb, 0xc0e7834240, 0x779})
	/usr/local/go1.17/src/runtime/mgc.go:594 +0x17a fp=0xc066de5db0 sp=0xc066de5d30 pc=0x101a35a
runtime.GC()
	/usr/local/go1.17/src/runtime/mgc.go:438 +0x45 fp=0xc066de5de8 sp=0xc066de5db0 pc=0x101a005
github.com/bytedance/sonic/issue_test_test.reloadSearchCtrCvrAdjust(0xc000184680, {0x1361022, 0x13c}, 0x0)
	/Users/admin/Desktop/kitex/sonic3/issue_test/issuex_test.go:75 +0x405 fp=0xc066de5f78 sp=0xc066de5de8 pc=0x12d3a45
github.com/bytedance/sonic/issue_test_test.TestIssueX.func1()
	/Users/admin/Desktop/kitex/sonic3/issue_test/issuex_test.go:91 +0xa5 fp=0xc066de5fe0 sp=0xc066de5f78 pc=0x12d3c85
runtime.goexit()
	/usr/local/go1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc066de5fe8 sp=0xc066de5fe0 pc=0x1068821
created by github.com/bytedance/sonic/issue_test_test.TestIssueX
	/Users/admin/Desktop/kitex/sonic3/issue_test/issuex_test.go:88 +0x57
```

**Comment by AsterDY** [comment]
#187
