### ISSUE TITLE
sonic.Unmarshal bug case

### ISSUE THREAD

**Issue by linez105** [bytedance/sonic#213]
sonic version: v1.1.1
golang version: go1.17.5 darwin/amd64

--------------------------------[code]---------------------------------------
```go
type DataSourceConfigJson struct {
	ProducerName      string
	ProducerBytes     []byte
	DegradeDataSource *DataSourceConfigJson
}

type DataConfigJson struct {
	DataSourceConfig *DataSourceConfigJson
}

func main() {
	bytes := []byte("{\"DataSourceConfig\":{\"ProducerName\":\"*main.DataSourceConfig\",\"ProducerBytes\":\"eyJUZXN0Q29kZSI6MjIyMiwiVGVzdFN0cmluZyI6InRlc3Rfc3RyaW5nMiJ9\",\"DegradeDataSource\":null}}")
	fmt.Println(string(bytes))
	var t *DataConfigJson
	fmt.Println("std-json:", json.Unmarshal(bytes, &t), t.DataSourceConfig)
	fmt.Println("jsoniter:", jsoniter.Unmarshal(bytes, &t), t.DataSourceConfig)
	fmt.Println("sonic:", sonic.Unmarshal(bytes, &t), t)
}
```
-------------------------------------[output]----------------------------------
```
{"DataSourceConfig":{"ProducerName":"*main.DataSourceConfig","ProducerBytes":"eyJUZXN0Q29kZSI6MjIyMiwiVGVzdFN0cmluZyI6InRlc3Rfc3RyaW5nMiJ9","DegradeDataSource":null}}
std-json: <nil> &{*main.DataSourceConfig [123 34 84 101 115 116 67 111 100 101 34 58 50 50 50 50 44 34 84 101 115 116 83 116 114 105 110 103 34 58 34 116 101 115 116 95 115 116 114 105 110 103 50 34 125] <nil>}
jsoniter: <nil> &{*main.DataSourceConfig [123 34 84 101 115 116 67 111 100 101 34 58 50 50 50 50 44 34 84 101 115 116 83 116 114 105 110 103 34 58 34 116 101 115 116 95 115 116 114 105 110 103 50 34 125] <nil>}
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x100d61f]

goroutine 1 [running]:
runtime.throw({0x1285933, 0xc000173828})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc0001737e8 sp=0xc0001737b8 pc=0x1031a51
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:742 +0x2f6 fp=0xc000173838 sp=0xc0001737e8 pc=0x1046fb6
runtime.evacuated(...)
        /usr/local/go/src/runtime/map.go:203
runtime.mapaccess1(0x1255ac0, 0xc000173a00, 0xc0001738d8)
        /usr/local/go/src/runtime/map.go:422 +0xbf fp=0xc000173878 sp=0xc000173838 pc=0x100d61f
github.com/bytedance/sonic/decoder.(*_Compiler).compileOne(0xc0001739e8, 0xc000173938, 0x106677e, {0x12ee350, 0x1248580})
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/compiler.go:519 +0x65 fp=0xc0001738f8 sp=0xc000173878 pc=0x11dc725
github.com/bytedance/sonic/decoder.(*_Compiler).compile(0x140a808, {0x12ee350, 0x1248580})
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/compiler.go:514 +0x99 fp=0xc000173980 sp=0xc0001738f8 pc=0x11dc5d9
github.com/bytedance/sonic/decoder.makeDecoder(0x1248580)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/pools.go:151 +0xf5 fp=0xc000173ad8 sp=0xc000173980 pc=0x11fa715
github.com/bytedance/sonic/internal/caching.(*ProgramCache).Compute(0xc0000964e0, 0x1248580, 0x0)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/internal/caching/pcache.go:166 +0x114 fp=0xc000173b58 sp=0xc000173ad8 pc=0x1196e74
github.com/bytedance/sonic/decoder.findOrCompile(0xc0001dc299)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/pools.go:161 +0xaf fp=0xc000173b80 sp=0xc000173b58 pc=0x11fa92f
github.com/bytedance/sonic/decoder.decodeTypedPointer({0xc0001dc210, 0xa6}, 0x1000, 0xc000448000, 0x105ad3a, 0x1196a71, 0xc000173c48)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/primitives.go:29 +0x45 fp=0xc000173c00 sp=0xc000173b80 pc=0x11faa05
runtime.__json_decoder_15ca000()
        ?:0 +0x2583 fp=0xc000173d00 sp=0xc000173c00 pc=0x15cc583
github.com/bytedance/sonic/decoder.decodeTypedPointer({0xc0001dc210, 0xa6}, 0xc0000a8580, 0x0, 0x0, 0x109c520, 0xc0000b0060)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/primitives.go:33 +0xb0 fp=0xc000173d80 sp=0xc000173d00 pc=0x11faa70
github.com/bytedance/sonic/decoder.(*Decoder).Decode(0xc000173e40, {0x12461c0, 0xc0000ae440})
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/decoder/decoder.go:73 +0xec fp=0xc000173e20 sp=0xc000173d80 pc=0x11e662c
github.com/bytedance/sonic.UnmarshalString({0xc0001dc210, 0xc0001dc000}, {0x12461c0, 0xc0000ae440})
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/sonic.go:46 +0x67 fp=0xc000173e90 sp=0xc000173e20 pc=0x12041a7
github.com/bytedance/sonic.Unmarshal(...)
        /Users/bytedance/local_go/pkg/mod/github.com/bytedance/sonic@v1.1.1/sonic.go:40
main.main()
        /Users/bytedance/local_go/src/test/gotest/main.go:28 +0x276 fp=0xc000173f80 sp=0xc000173e90 pc=0x1239ad6
runtime.main()
        /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc000173fe0 sp=0xc000173f80 pc=0x10340e7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000173fe8 sp=0xc000173fe0 pc=0x1060021
exit status 2
```

**Comment by ii64** [comment]
```go
var t *DataConfigJson
```
Seems you declare null pointer, and pass it as reference to sonic.

**Comment by linez105** [comment]
> ```go
> var t *DataConfigJson
> ```
> 
> Seems you declare null pointer, and pass it as reference to sonic.

Yes, but standard json and jsoniter seem fine.

**Comment by AsterDY** [comment]
We find it is `ProducerBytes  []byte` that causes the problem,  but we are still working on fixing it. As a work-around, you can use `ProducerBytes string` instead and decode it subsequently using `encoding/base64.Decode()`. We will inform you as soon as we fix it.
