### ISSUE TITLE
生产环境报错，程序重启，求救。

### ISSUE THREAD

**Issue by lxj15398019970** [bytedance/sonic#236]
生产环境偶尔报这个错误，recover不到这个异常，导致程序重启。

```
traceback: unexpected SPWRITE function github.com/bytedance/sonic/internal/native/avx2.__native_entry__
fatal error: traceback

runtime stack:
runtime.throw({0x12ef91c, 0x1de4260})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.gentraceback(0x7fc3972db850, 0x1580, 0xc01949fba0, 0xc0eb5aa4e0, 0x0, 0x0, 0x7fffffff, 0x7fc385ff7460, 0x400000002, 0x0)
	/usr/local/go/src/runtime/traceback.go:238 +0x19c5
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:751 +0x6b
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:383 +0x49

goroutine 6113840 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc000367488 sp=0xc000367480 pc=0x4d08a0
runtime.addOneOpenDeferFrame(0xc8, 0x1fffffff, 0x47012d)
	/usr/local/go/src/runtime/panic.go:750 +0x77 fp=0xc0003674c8 sp=0xc000367488 pc=0x49e537
panic({0x11df0a0, 0x1d84b40})
	/usr/local/go/src/runtime/panic.go:998 +0x114 fp=0xc000367588 sp=0xc0003674c8 pc=0x49f354
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:221
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:735 +0x327 fp=0xc0003675d8 sp=0xc000367588 pc=0x4b5c47
github.com/bytedance/sonic/internal/native/avx2.__native_entry__()
	/data/gopath/pkg/mod/github.com/bytedance/sonic@v1.1.1/internal/native/avx2/native_amd64.s:1618 +0x1565 fp=0xc0003675e0 sp=0xc0003675d8 pc=0x910925
created by gateway/handler.selectAppItemsBidResponse
	/home/ubuntu/remotejenkins/workspace/Gears_Docker_tar2/dsp-gateway/src/handler/dispatcher-handler.go:114 +0x2af
```

**Comment by lxj15398019970** [comment]
> 1. Sonic 版本？
> 2. OS 版本？
> 3. Go 版本？
> 4. 能否提供报错时的结构体 / 数据？

go 1.17
sonic 1.1.1
centos：Linux version 3.10.0-1160.15.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) 

这个异常无法recover住，程序直接挂掉，所以拿不到报错时的数据。

**Comment by AsterDY** [comment]
升级到最新版看看

**Comment by chenzhuoyu** [comment]
@AsterDY 看起来是在 native 函数里 panic 了

**Comment by chenzhuoyu** [comment]
@AsterDY 还是 [avx2/native_amd64.s:1618](https://github.com/bytedance/sonic/blob/v1.1.1/internal/native/avx2/native_amd64.s#L1618) 的 `vmovdqu`，跟之前的 nil panic 在同一个地方，应该是同一个原因。

@lxj15398019970 升级一下最新版，这个问题在新版本里修复了
