### ISSUE TITLE
sonic 1.18 crash in test with -race

### ISSUE THREAD

**Issue by TomasVojacek** [bytedance/sonic#363]
sonic 1.18
go version go1.19.5 linux/amd64

go test -race

```
import (
	"testing"

	"github.com/bytedance/sonic"
)

func TestUmmarshal(t *testing.T) {
	var o int
	raw := []byte{'0'}
	err := sonic.Unmarshal(raw, &o)
	if err!=nil{
          t.Fail()
       }
}
```

```
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 1 [running, locked to thread]:
runtime.throw({0x86400d?, 0xc000241910?})
	/snap/go/current/src/runtime/panic.go:1047 +0x5d fp=0xc0001d4f10 sp=0xc0001d4ee0 pc=0x46dafd
runtime.checkptrAlignment(0xb?, 0x811e00?, 0xc000241800?)
	/snap/go/current/src/runtime/checkptr.go:26 +0x6c fp=0xc0001d4f30 sp=0xc0001d4f10 pc=0x43d10c
github.com/bytedance/sonic/internal/rt.(*StackMapBuilder).Build(0xc0001d5048)
	go/pkg/mod/github.com/bytedance/sonic@v1.8.0/internal/rt/stackmap.go:160 +0x89 fp=0xc0001d4fa0 sp=0xc0001d4f30 pc=0x700a29
github.com/bytedance/sonic/loader.Loader.LoadOne({{0x8538c2, 0xa}, {0x85ea6a, 0x21}, {0x1}}, {0xc00022c000, 0xf39, 0x1185}, {0x8550cb, 0xc}, ...)
	go/pkg/mod/github.com/bytedance/sonic@v1.8.0/loader/loader_go118.go:79 +0x572 fp=0xc0001d5258 sp=0xc0001d4fa0 pc=0x7064d2
github.com/bytedance/sonic/internal/jit.(*BaseAssembler).Load(0xc000078300, {0x8550cb, 0xc}, 0x7fbba1b22938?, 0x58?, {0xa90320, 0x1, 0x1}, {0xb3c400, 0x0, ...})
	go/pkg/mod/github.com/bytedance/sonic@v1.8.0/internal/jit/assembler_amd64.go:215 +0x196 fp=0xc0001d5338 sp=0xc0001d5258 pc=0x70a2b6
github.com/bytedance/sonic/decoder.(*_ValueDecoder).build(0xc000078300)
	go/pkg/mod/github.com/bytedance/sonic@v1.8.0/decoder/generic_amd64_go117.go:88 +0x21e fp=0xc0001d53e8 sp=0xc0001d5338 pc=0x7d557e
github.com/bytedance/sonic/decoder.init()
	go/pkg/mod/github.com/bytedance/sonic@v1.8.0/decoder/generic_amd64_go117.go:766 +0x8976 fp=0xc0001d7ac0 sp=0xc0001d53e8 pc=0x7f8fb6
runtime.doInit(0xa98ae0)
	/snap/go/current/src/runtime/proc.go:6329 +0x126 fp=0xc0001d7bf0 sp=0xc0001d7ac0 pc=0x47d9e6
runtime.doInit(0xa94e80)
	/snap/go/current/src/runtime/proc.go:6306 +0x71 fp=0xc0001d7d20 sp=0xc0001d7bf0 pc=0x47d931
runtime.doInit(0xa92b60)
	/snap/go/current/src/runtime/proc.go:6306 +0x71 fp=0xc0001d7e50 sp=0xc0001d7d20 pc=0x47d931
runtime.doInit(0xa94160)
	/snap/go/current/src/runtime/proc.go:6306 +0x71 fp=0xc0001d7f80 sp=0xc0001d7e50 pc=0x47d931
runtime.main()
	/snap/go/current/src/runtime/proc.go:233 +0x1d3 fp=0xc0001d7fe0 sp=0xc0001d7f80 pc=0x470313
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0001d7fe8 sp=0xc0001d7fe0 pc=0x49fda1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:363 +0xd6 fp=0xc00004efb0 sp=0xc00004ef90 pc=0x470716
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:369
runtime.forcegchelper()
	/snap/go/current/src/runtime/proc.go:302 +0xad fp=0xc00004efe0 sp=0xc00004efb0 pc=0x4705ad
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004efe8 sp=0xc00004efe0 pc=0x49fda1
created by runtime.init.6
	/snap/go/current/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:363 +0xd6 fp=0xc00004f790 sp=0xc00004f770 pc=0x470716
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/snap/go/current/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00004f7c8 sp=0xc00004f790 pc=0x45b1ee
runtime.gcenable.func1()
	/snap/go/current/src/runtime/mgc.go:178 +0x26 fp=0xc00004f7e0 sp=0xc00004f7c8 pc=0x44fec6
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004f7e8 sp=0xc00004f7e0 pc=0x49fda1
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000022070?, 0x9251a8?, 0x1?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:363 +0xd6 fp=0xc00004ff70 sp=0xc00004ff50 pc=0x470716
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xafd1c0)
	/snap/go/current/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00004ffa0 sp=0xc00004ff70 pc=0x4592b3
runtime.bgscavenge(0x0?)
	/snap/go/current/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00004ffc8 sp=0xc00004ffa0 pc=0x459865
runtime.gcenable.func2()
	/snap/go/current/src/runtime/mgc.go:179 +0x26 fp=0xc00004ffe0 sp=0xc00004ffc8 pc=0x44fe66
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004ffe8 sp=0xc00004ffe0 pc=0x49fda1
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0xc000007860?, 0x0?, 0x0?, 0x5?, 0xc00004e770?)
	/snap/go/current/src/runtime/proc.go:363 +0xd6 fp=0xc00004e628 sp=0xc00004e608 pc=0x470716
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:369
runtime.runfinq()
	/snap/go/current/src/runtime/mfinal.go:180 +0x145 fp=0xc00004e7e0 sp=0xc00004e628 pc=0x44efe5
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x49fda1
created by runtime.createfing
	/snap/go/current/src/runtime/mfinal.go:157 +0x45

Process finished with the exit code 1
```

**Comment by AsterDY** [comment]
fixed by #365
