### ISSUE TITLE
panic: unexpected fault address 0xc003000000

### ISSUE THREAD

**Issue by intfish123** [bytedance/sonic#523]
It's happend occasionally too...
sonic-json version: `v1.10.0`
```
unexpected fault address 0xc003000000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc003000000 pc=0x7fb681597100]

goroutine 28 [running]:
runtime.throw({0x196697f?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc001bc4ab0 sp=0xc001bc4a80 pc=0x44957d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc001bc4b00 sp=0xc001bc4ab0 pc=0x45f2e5
_do_skip_number()
	avx/native.c:1 +0xd0 fp=0xc001bc4b38 sp=0xc001bc4b00 pc=0x7fb681597100
_value()
	avx/native.c:1 +0x237 fp=0xc001bc4b98 sp=0xc001bc4b38 pc=0x7fb681595257
decode_value()
	?:0 +0x1ab fp=0xc001bc4c78 sp=0xc001bc4b98 pc=0x7fb68137c1ab
decode_()
	?:0 +0xcea fp=0xc001bc4d98 sp=0xc001bc4c78 pc=0x7fb680bfccea
github.com/bytedance/sonic/internal/decoder.decodeTypedPointer({0xc002fff000, 0xff5}, 0x2c33343030373837?, 0x747379735f647022?, 0x69737265765f6d65?, 0x2265646f635f6e6f?, 0x7d39323a?)
	/go/pkg/mod/github.com/bytedance/sonic@v1.10.0/internal/decoder/primitives.go:34 +0xdb fp=0xc001bc4e30 sp=0xc001bc4d98 pc=0x15dc0db
github.com/bytedance/sonic/internal/decoder.(*Decoder).Decode(0xc00057de78, {0x1803e00?, 0xc000015b00})
	/go/pkg/mod/github.com/bytedance/sonic@v1.10.0/internal/decoder/decoder.go:142 +0x25b fp=0xc001bc4f18 sp=0xc001bc4e30 pc=0x15c7f7b
github.com/bytedance/sonic/internal/decoder.(*StreamDecoder).Decode(0xc00057de30, {0x1803e00, 0xc000015b00})
	/go/pkg/mod/github.com/bytedance/sonic@v1.10.0/internal/decoder/stream.go:114 +0x4d0 fp=0xc001bc5008 sp=0xc001bc4f18 pc=0x15dc8d0
gosinker/output.(*ClickhouseNode).cleanColumn(0xc000156000, {0xc002ffe000, 0xff5, 0xff5})
	/build/output/clickhouse.go:1054 +0x275 fp=0xc001bc5250 sp=0xc001bc5008 pc=0x1625b75
gosinker/output.(*ClickhouseNode).StartWriteData.func3()
	/build/output/clickhouse.go:275 +0xb32 fp=0xc001bc5fe0 sp=0xc001bc5250 pc=0x161c092
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc001bc5fe8 sp=0xc001bc5fe0 pc=0x47aa41
created by gosinker/output.(*ClickhouseNode).StartWriteData
	/build/output/clickhouse.go:205 +0x185
```

**Comment by intfish123** [comment]
@liuq19  Is same as https://github.com/bytedance/sonic/issues/507#issue-1854587484

**Comment by liuq19** [comment]
yes, maybe the same reason. could you try the master branch~

**Comment by NewbieOrange** [comment]
@AsterDY can you tag a new fixed version?

**Comment by AsterDY** [comment]
> @AsterDY can you tag a new fixed version?

https://github.com/bytedance/sonic/releases/tag/v1.10.1 done @NewbieOrange
