### ISSUE TITLE
panic when using nil *Time pointer

### ISSUE THREAD

**Issue by loggerhead** [bytedance/sonic#58]
```go
package main

import (
	"github.com/bytedance/sonic"
	"time"
)

func main() {
	a := struct {
		T *time.Time
	}{}
	sonic.Marshal(&a)
}
```

**Comment by loggerhead** [comment]
panic msg:

```bash
panic: value method time.Time.MarshalJSON called using nil *Time pointer

goroutine 1 [running]:
time.(*Time).MarshalJSON(0x0, 0x0, 0x4286e7c500000000, 0xc0001cdd80, 0x0, 0x0)
	<autogenerated>:1 +0x93
github.com/bytedance/sonic/encoder.encodeJsonMarshaler(0xc0000a63a8, 0x2cb1160, 0x0, 0x0, 0x0)
	/Users/tyrionlong/go/pkg/mod/github.com/bytedance/sonic@v0.0.0-20210723083932-f9632ab87317/encoder/primitives.go:82 +0x31
github.com/bytedance/sonic/encoder.encodeTypedPointer(0xc0000a63a8, 0x125b020, 0xc000010028, 0xc000300000, 0x0, 0xc000165ed0)
	/Users/tyrionlong/go/pkg/mod/github.com/bytedance/sonic@v0.0.0-20210723083932-f9632ab87317/encoder/primitives.go:77 +0x163
github.com/bytedance/sonic/encoder.EncodeInto(0xc0000a63a8, 0x125b020, 0xc0000be1d0, 0xc000200000, 0xc000165f30)
	/Users/tyrionlong/go/pkg/mod/github.com/bytedance/sonic@v0.0.0-20210723083932-f9632ab87317/encoder/encoder.go:67 +0xc5
github.com/bytedance/sonic/encoder.Encode(0x125b020, 0xc0000be1d0, 0x1019701, 0x0, 0x0, 0x125d560, 0xc00008c058)
	/Users/tyrionlong/go/pkg/mod/github.com/bytedance/sonic@v0.0.0-20210723083932-f9632ab87317/encoder/encoder.go:47 +0xbb
github.com/bytedance/sonic.Marshal(...)
	/Users/tyrionlong/go/pkg/mod/github.com/bytedance/sonic@v0.0.0-20210723083932-f9632ab87317/sonic.go:30
main.main()
	/Users/tyrionlong/Downloads/foo/main.go:12 +0x3d
exit status 2
```
